jobs:
  validate:
    docker:
    - auth:
        password: $DOCKER_PASSWORD
        username: $DOCKER_USERNAME
      image: trussworks/circleci:efb1042e31538677779971798e0912390f699e72
    steps:
    - checkout
    - restore_cache:
        keys:
        - pre-commit-dot-cache-{{ checksum ".pre-commit-config.yaml" }}
    - run:
        command: pre-commit run --all-files
        name: Run pre-commit tests
    - save_cache:
        key: pre-commit-dot-cache-{{ checksum ".pre-commit-config.yaml" }}
        paths:
        - ~/.cache/pre-commit
version: 2.1
workflows:
  validate:
    jobs:
    - validate:
        context:
        - org-global
  version: 2.1
